version: '3.4'

services:
    user.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ConnectionString=Host=sql.data;Username=postgres;Password=Password1!;Database=chitchat_users
        ports:
            - "81:80"
    discussion.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ConnectionString=Host=sql.data;Username=postgres;Password=Password1!;Database=chitchat_discussion
        ports:
            - "82:80"
    reports.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ConnectionString=Host=sql.data;Username=postgres;Password=Password1!;Database=chitchat_reports
        ports:
            - "83:80"
    cache.data:
        ports:
            - "6379:6379"
    sql.data:
        environment:
            POSTGRES_PASSWORD: Password1!
        ports:
            - "5433:5432"
    noSql.data:
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: Password1!
    rabbitmq:
        ports:
            - "15672:15672"
            - "5672:5672"
    adminer:
        ports:
            - 8080:8080
    mongo-express:
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: Password1!