version: "3.4"
services:
    user.api:
        image: chit-chat-api/user-api:${TAG:-latest}
        build:
            context: .
            dockerfile: src/user-api/dockerfile
        depends_on:
            - sql.data
            - rabbitmq
    discussion.api:
        image: chit-chat-api/discussion-api:${TAG:-latest}
        build:
            context: .
            dockerfile: src/discussion-api/dockerfile
        depends_on:
            - sql.data
            - rabbitmq
    reports.api:
        image: chit-chat-api/reports-api:${TAG:-latest}
        build:
            context: .
            dockerfile: src/reports-api/dockerfile
        depends_on:
            - sql.data
            - rabbitmq
    cacche.data:
        image: redis
    sql.data:
        image: postgres:latest
        restart: always
    rabbitmq:
        image: rabbitmq:3-management
    adminer:
        image: adminer
        restart: always
        depends_on:
            - sql.data
    mobile.bff:
        image: chit-chat-api/api-gateway/mobile-bff:${TAG:-latest}
        build:
            context: .
            dockerfile: src/api-gateway/mobile-bff/dockerfile
        depends_on:
            - user.api
            - discussion.api
            - reports.api
            - sql.data
            - rabbitmq
    web.bff:
        image: chit-chat-api/api-gateway/web-bff:${TAG:-latest}
        build:
            context: .
            dockerfile: src/api-gateway/web-bff/dockerfile
        depends_on:
            - user.api
            - discussion.api
            - reports.api
            - sql.data
            - rabbitmq