version: "3.4"
services:
    user.api:
        image: chit-chat-api/user-api
        environment:
            - ConnectionString=Host=sql.data;Username=postgres;Password=Password1!;Database=users
        ports:
            - "81:80"
        depends_on:
            - sql.data
            - rabbitmq
    discussion.api:
        image: chit-chat-api/discussion-api
        environment:
            - ConnectionString=Host=sql.data;Username=postgres;Password=Password1!;Database=discussion
        ports:
            - "82:80"
        depends_on:
            - sql.data
            - rabbitmq
    reports.api:
        image: chit-chat-api/reports-api
        environment:
            - ConnectionString=Host=sql.data;Username=postgres;Password=Password1!;Database=reports
        ports:
            - "83:80"
        depends_on:
            - sql.data
            - rabbitmq
    basket.data:
        image: redis
    sql.data:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: Password1!
    rabbitmq:
        image: rabbitmq:3-management
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - sql.data